### ISSUE TITLE
does not work on Android Oreo

### ISSUE THREAD

**Issue by GorvGoyl** [micer/clipboard-service#1]
I tested on my (rooted with magisk) one plus 6 phone having android Oreo.

Here's the response I got:
```
> am service -a eu.micer.ClipboardService -e text "SampleText"
> Starting service: Intent { act=eu.micer.ClipboardService (has extras) }
Error: Not found; no service started.
```

**Comment by micer** [comment]
Hey @JerryGoyal. Please note, that the correct command is:

`adb shell am startservice -a eu.micer.ClipboardService -e text "SampleText"`

It can happen that you get this error:
```
 ~ adb shell am startservice -a eu.micer.ClipboardService -e text "SampleText"
Starting service: Intent { act=eu.micer.ClipboardService (has extras) }
Error: app is in background uid null
```

You just need to start the app via command:
```
adb shell am start -n eu.micer.clipboardservice/eu.micer.clipboardservice.EmptyActivity
```
or find the **ClipboardService** in the app list and start it manually. I'm running the app on OnePlus 5 with Oreo as well without any issues. Let me know, if it's working for you.
